controller_manager:
  ros__parameters:
    update_rate: 100

    rb1_base_controller:
      type: diff_drive_controller/DiffDriveController
    
    rb1_elevator_controllers:
      type: effort_controllers/JointGroupEffortController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rb1_base_controller:
  ros__parameters:
    left_wheel_names: ["robot_left_wheel_joint"]
    right_wheel_names: ["robot_right_wheel_joint"]

    wheel_separation: 0.436
    wheel_radius: 0.076
    
    publish_rate: 100.0
    use_stamped_vel: false
    open_loop: true
    
    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_link

rb1_elevator_controllers:
  ros__parameters:
    joints:
      - robot_elevator_platform_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort